/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
function optToCandid<T>(opt: Option<T>): [] | [T] {
    return isSome(opt) ? candid_some(opt.value) : candid_none();
}
function candidToOpt<T>(candid: [] | [T]): Option<T> {
    return (candid as any[]).length === 0 ? none() : some((candid as any[])[0]);
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}

export interface backendInterface {
    registerUser(name: string, username: string, password: string): Promise<Option<any>>;
    loginUser(username: string, password: string): Promise<Option<any>>;
    getUserCount(): Promise<bigint>;
    addDutyEntry(input: any): Promise<bigint>;
    getAllDutyEntries(): Promise<any[]>;
    getDutyEntriesByUser(userId: bigint): Promise<any[]>;
    getDutyEntry(id: bigint): Promise<Option<any>>;
    updateDutyEntry(id: bigint, input: any): Promise<boolean>;
    deleteDutyEntry(id: bigint): Promise<boolean>;
    addLeaveEntry(input: any): Promise<bigint>;
    getAllLeaveEntries(): Promise<any[]>;
    getLeaveEntriesByUser(userId: bigint): Promise<any[]>;
    getLeaveEntry(id: bigint): Promise<Option<any>>;
    updateLeaveEntry(id: bigint, input: any): Promise<boolean>;
    deleteLeaveEntry(id: bigint): Promise<boolean>;
    addUpcomingDuty(input: any): Promise<bigint>;
    getAllUpcomingDuties(): Promise<any[]>;
    getUpcomingDutiesByUser(userId: bigint): Promise<any[]>;
    getUpcomingDuty(id: bigint): Promise<Option<any>>;
    updateUpcomingDuty(id: bigint, input: any): Promise<boolean>;
    deleteUpcomingDuty(id: bigint): Promise<boolean>;
    markUpcomingDutyCompleted(id: bigint): Promise<boolean>;
    markUpcomingDutyMissed(id: bigint): Promise<boolean>;
}

function dutyInputToCandid(input: any): any {
    return {
        userId: input.userId,
        dutyDate: input.dutyDate,
        reportingTime: optToCandid(input.reportingTime),
        workType: input.workType,
        dutyRole: input.dutyRole,
        centreOfDuty: optToCandid(input.centreOfDuty),
        orderNo: input.orderNo,
        remunerationAmount: input.remunerationAmount,
        remunerationCredited: input.remunerationCredited,
        remunerationCreditDate: optToCandid(input.remunerationCreditDate),
        taEligible: input.taEligible,
        taAmount: optToCandid(input.taAmount),
        taSubmissionStatus: optToCandid(input.taSubmissionStatus),
        taCredited: optToCandid(input.taCredited),
        taCreditDate: optToCandid(input.taCreditDate),
        orderDocumentId: optToCandid(input.orderDocumentId),
        remarks: optToCandid(input.remarks),
    };
}

function dutyFromCandid(entry: any): any {
    return {
        id: entry.id,
        userId: entry.userId,
        dutyDate: entry.dutyDate,
        reportingTime: candidToOpt(entry.reportingTime),
        workType: entry.workType,
        dutyRole: entry.dutyRole,
        centreOfDuty: candidToOpt(entry.centreOfDuty ?? []),
        orderNo: entry.orderNo,
        remunerationAmount: entry.remunerationAmount,
        remunerationCredited: entry.remunerationCredited,
        remunerationCreditDate: candidToOpt(entry.remunerationCreditDate),
        taEligible: entry.taEligible,
        taAmount: candidToOpt(entry.taAmount),
        taSubmissionStatus: candidToOpt(entry.taSubmissionStatus),
        taCredited: candidToOpt(entry.taCredited),
        taCreditDate: candidToOpt(entry.taCreditDate),
        orderDocumentId: candidToOpt(entry.orderDocumentId),
        remarks: candidToOpt(entry.remarks),
        createdAt: entry.createdAt,
    };
}

function leaveInputToCandid(input: any): any {
    return {
        userId: input.userId,
        leaveType: input.leaveType,
        holidayDutyDate: optToCandid(input.holidayDutyDate),
        sanctionedDate: optToCandid(input.sanctionedDate),
        sanctionedOD: optToCandid(input.sanctionedOD),
        orderDocumentLeaveId: optToCandid(input.orderDocumentLeaveId),
        orderNumber: input.orderNumber,
        availed: input.availed,
        availedDates: input.availedDates,
        remarks: optToCandid(input.remarks),
    };
}

function leaveFromCandid(entry: any): any {
    return {
        id: entry.id,
        userId: entry.userId,
        leaveType: entry.leaveType,
        holidayDutyDate: candidToOpt(entry.holidayDutyDate),
        sanctionedDate: candidToOpt(entry.sanctionedDate),
        sanctionedOD: candidToOpt(entry.sanctionedOD),
        orderDocumentLeaveId: candidToOpt(entry.orderDocumentLeaveId),
        orderNumber: entry.orderNumber,
        availed: entry.availed,
        availedDates: entry.availedDates,
        remarks: candidToOpt(entry.remarks),
        createdAt: entry.createdAt,
    };
}

function upcomingInputToCandid(input: any): any {
    return {
        userId: input.userId,
        dutyDate: input.dutyDate,
        reportingTime: input.reportingTime,
        workType: input.workType,
        dutyRole: input.dutyRole,
        centreOfDuty: optToCandid(input.centreOfDuty),
        orderNumber: input.orderNumber,
        reminderEnabled: input.reminderEnabled,
        status: input.status,
    };
}

function upcomingFromCandid(entry: any): any {
    return {
        id: entry.id,
        userId: entry.userId,
        dutyDate: entry.dutyDate,
        reportingTime: entry.reportingTime,
        workType: entry.workType,
        dutyRole: entry.dutyRole,
        centreOfDuty: candidToOpt(entry.centreOfDuty ?? []),
        orderNumber: entry.orderNumber,
        reminderEnabled: entry.reminderEnabled,
        status: entry.status,
        createdAt: entry.createdAt,
    };
}

export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}

    async registerUser(name: string, username: string, password: string): Promise<Option<any>> {
        const result = await this.actor.registerUser(name, username, password);
        return candidToOpt(result);
    }

    async loginUser(username: string, password: string): Promise<Option<any>> {
        const result = await this.actor.loginUser(username, password);
        return candidToOpt(result);
    }

    async getUserCount(): Promise<bigint> {
        return this.actor.getUserCount();
    }

    async addDutyEntry(input: any): Promise<bigint> {
        return this.actor.addDutyEntry(dutyInputToCandid(input));
    }

    async getAllDutyEntries(): Promise<any[]> {
        const entries = await this.actor.getAllDutyEntries();
        return entries.map(dutyFromCandid);
    }

    async getDutyEntriesByUser(userId: bigint): Promise<any[]> {
        const entries = await this.actor.getDutyEntriesByUser(userId);
        return entries.map(dutyFromCandid);
    }

    async getDutyEntry(id: bigint): Promise<Option<any>> {
        const result = await this.actor.getDutyEntry(id);
        if ((result as any[]).length === 0) return none();
        return some(dutyFromCandid((result as any[])[0]));
    }

    async updateDutyEntry(id: bigint, input: any): Promise<boolean> {
        return this.actor.updateDutyEntry(id, dutyInputToCandid(input));
    }

    async deleteDutyEntry(id: bigint): Promise<boolean> {
        return this.actor.deleteDutyEntry(id);
    }

    async addLeaveEntry(input: any): Promise<bigint> {
        return this.actor.addLeaveEntry(leaveInputToCandid(input));
    }

    async getAllLeaveEntries(): Promise<any[]> {
        const entries = await this.actor.getAllLeaveEntries();
        return entries.map(leaveFromCandid);
    }

    async getLeaveEntriesByUser(userId: bigint): Promise<any[]> {
        const entries = await this.actor.getLeaveEntriesByUser(userId);
        return entries.map(leaveFromCandid);
    }

    async getLeaveEntry(id: bigint): Promise<Option<any>> {
        const result = await this.actor.getLeaveEntry(id);
        if ((result as any[]).length === 0) return none();
        return some(leaveFromCandid((result as any[])[0]));
    }

    async updateLeaveEntry(id: bigint, input: any): Promise<boolean> {
        return this.actor.updateLeaveEntry(id, leaveInputToCandid(input));
    }

    async deleteLeaveEntry(id: bigint): Promise<boolean> {
        return this.actor.deleteLeaveEntry(id);
    }

    async addUpcomingDuty(input: any): Promise<bigint> {
        return this.actor.addUpcomingDuty(upcomingInputToCandid(input));
    }

    async getAllUpcomingDuties(): Promise<any[]> {
        const entries = await this.actor.getAllUpcomingDuties();
        return entries.map(upcomingFromCandid);
    }

    async getUpcomingDutiesByUser(userId: bigint): Promise<any[]> {
        const entries = await this.actor.getUpcomingDutiesByUser(userId);
        return entries.map(upcomingFromCandid);
    }

    async getUpcomingDuty(id: bigint): Promise<Option<any>> {
        const result = await this.actor.getUpcomingDuty(id);
        if ((result as any[]).length === 0) return none();
        return some(upcomingFromCandid((result as any[])[0]));
    }

    async updateUpcomingDuty(id: bigint, input: any): Promise<boolean> {
        return this.actor.updateUpcomingDuty(id, upcomingInputToCandid(input));
    }

    async deleteUpcomingDuty(id: bigint): Promise<boolean> {
        return this.actor.deleteUpcomingDuty(id);
    }

    async markUpcomingDutyCompleted(id: bigint): Promise<boolean> {
        return this.actor.markUpcomingDutyCompleted(id);
    }

    async markUpcomingDutyMissed(id: bigint): Promise<boolean> {
        return this.actor.markUpcomingDutyMissed(id);
    }
}

export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
